name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Run .NET Build
        run: dotnet build --no-restore

      - name: Run Unit Tests
        run: dotnet test InversionOfControl.Tests/InversionOfControl.Tests.csproj