name: Deploy Nuget Package

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Restore Nuget Packages
        run: dotnet restore

      - name: Run .NET Build
        run: dotnet build --no-restore

      - name: Run Unit Tests
        run: dotnet test InversionOfControl.Tests/InversionOfControl.Tests.csproj

      - name: Install Nuget Tool 6.2.0
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '6.2.0'

      - name: Deploy Nuget Package
        run: |
          cd InversionOfControl.Core
          nuget spec InversionOfControl.Core.csproj
          dotnet nuget push InversionOfControl.Core.nuspec --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}